# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dda5d74c-5a5d-4281-b24f-700e58985e0e";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ]; 
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/dda5d74c-5a5d-4281-b24f-700e58985e0e";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ]; 
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/dda5d74c-5a5d-4281-b24f-700e58985e0e";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ]; 
    };


fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/dda5d74c-5a5d-4281-b24f-700e58985e0e";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" ]; 
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/554F-2F71";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/ssd_2" =
    { device = "/dev/disk/by-uuid/b11ae039-3d9b-41d4-85a2-7382a447e4d1";
      fsType = "btrfs";
      options = [ "compress=zstd" "nofail" "noatime" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
