# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f45088f3-942f-4a7e-91eb-e5af7d7dbf14";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f45088f3-942f-4a7e-91eb-e5af7d7dbf14";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f45088f3-942f-4a7e-91eb-e5af7d7dbf14";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/f45088f3-942f-4a7e-91eb-e5af7d7dbf14";
      fsType = "btrfs";
      options = [ "subvol=@log" "noatime" "compress=zstd" ];
    };

  fileSystems."/mnt/ssd1" =
    { device = "/dev/disk/by-uuid/f45088f3-942f-4a7e-91eb-e5af7d7dbf14";
      fsType = "btrfs";
      options = [ "subvol=@storage" "noatime" "compress=zstd" ];
    };

  fileSystems."/mnt/ssd2" =
    { device = "/dev/disk/by-uuid/415b1c08-868f-45bd-b853-aad84665f199";
      fsType = "btrfs";
      options = [ "subvol=@"  "noatime" "compress=zstd" ];
    };

  fileSystems."/mnt/root" =
    { device = "/dev/disk/by-uuid/f45088f3-942f-4a7e-91eb-e5af7d7dbf14";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6A82-9442";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0c877173-07eb-47ff-9037-4b36f8a630fb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
