# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D615-8540";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/88ca4837-8810-4c6e-a52a-5cfa068cf664";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "space_cache=v2" "ssd" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/88ca4837-8810-4c6e-a52a-5cfa068cf664";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "space_cache=v2" "ssd" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/88ca4837-8810-4c6e-a52a-5cfa068cf664";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" "space_cache=v2" "ssd" "discard=async" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/88ca4837-8810-4c6e-a52a-5cfa068cf664";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" "space_cache=v2" "ssd" "discard=async" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
